import { joi } from "@structured-growth/microservice-sdk";

export const MetricSearchParamsValidator = joi.object({
	query: joi.object({
		id: joi.array().items(joi.string().required()).label("Metric Id"),
		orgId: joi.number().positive().label("Organization Id"),
		metricCategoryId: joi.number().positive().label("Metric Type Id"),
		metricCategoryCode: joi.string().max(50).min(1).label("Metric Type Code"),
		metricTypeId: joi.array().items(joi.number().positive()).label("Metric Type Id"),
		metricTypeCode: joi.array().items(joi.string().max(50).min(1)).label("Metric Type Code"),
		metricTypeVersion: joi.number().positive().label("Metric Type Version"),
		accountId: joi.array().items(joi.number().positive()).label("Account Id"),
		userId: joi.array().items(joi.number().positive()).label("User Id"),
		relatedToRn: joi.string().max(50).label("Related To"),
		deviceId: joi.number().positive().label("Device ID"),
		batchId: joi.string().max(50).label("Batch id"),
		value: joi.number().label("Value"),
		valueMin: joi.number().label("Value Minimum"),
		valueMax: joi.number().label("Value Maximum"),
		takenAtMin: joi.date().iso().label("Taken at minimum"),
		takenAtMax: joi.date().iso().label("Taken at maximum"),
		takenAtOffset: joi.number().label("Taken at Offset"),
		recordedAtMin: joi.date().iso().label("Recorded at minimum"),
		recordedAtMax: joi.date().iso().label("Recorded at maximum"),
		limit: joi.number().positive().label("Limit"),
		sort: joi.array().items(joi.string().required()).label("Sort"),
		page: joi.number().positive().label("Page"),
		nextToken: joi.string().label("Next Token"),
	}),
});
